# Testing for CamelUp Algorithm
### import of code

In [35]:
%load_ext autoreload
%autoreload 2

from CamelUp import *


The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


### precompile njit functions:

In [36]:
"""
demo_players = {"Player 1":player("Player 1"),"Player 2":player("Player 2"),
                "Player 3":player("Player 3"),"Player 4":player("Player 4")}
demo_precompilation = Field([
    [], [], [], [], [], ['Yellow', 'Green'], ['Purple', 'Blue', 'Orange'], ["DESERT", "Player 1"], [], 
    ["Black", "White"], [], [], [], [],[], [], [], [], []],copy.deepcopy(demo_players))
n_camels_thrown = 4
camels_not_thrown = [1,2]
game_inventory_matrix = np.array([[1,1,2]]*5)
rendered_field, inv_player_mask = render_field(demo_precompilation.game_field,demo_precompilation.players)
positions, DO_hits, VOI = sim_all_moves(rendered_field, 4, n_camels_thrown, camels_not_thrown, game_inventory_matrix, verbose=False)
positions, DO_hits, VOI
"""
print()

### Some base field 4 players

In [38]:
demo_players = {"Player 1":player("Player 1"),"Player 2":player("Player 2"),
                "Player 3":player("Player 3"),"Player 4":player("Player 4")}
demoE = Field([
    [], [], [], [], [], ['YELLOW', 'GREEN'], ['PURPLE', 'BLUE', 'ORANGE'], [], [], 
    ["BLACK", "WHITE"], [], [], [], [],[], [], [], [], []],copy.deepcopy(demo_players))

## Init function with pre-defined players and game field
Test_0_1 = CamelUp(4,field = demoE,black_white=True,user_guide=True)

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[41, 126]

                                           #####################                                       
                                           ##  Current Field  ##                                       
                                           #####################                                       

     ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                   

In [ ]:
demo_players = {"Player 1":player("Player 1"),"Player 2":player("Player 2"),
                "Player 3":player("Player 3"),"Player 4":player("Player 4")}
demo2 = Field([
    [], [], [], [], [], ['YELLOW', 'GREEN'], ["BLACK", 'PURPLE', 'BLUE'], ["DESERT","Player 1"], [], 
    ["WHITE", 'ORANGE'], ["DESERT","Player 2"], [], [], [],[], [], [], [], []],copy.deepcopy(demo_players))

## Init function with pre-defined players and game field
Test_0_2 = CamelUp(4,field = demo2,black_white=True,user_guide=True)

————————————————————————————————————————————————————————————————————————————————————————————————————————————————————
[41, 126]

                                           #####################                                       
                                           ##  Current Field  ##                                       
                                           #####################                                       

     ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                   

In [34]:
Test_0_1._desert_iterator("Player 1",verbose=1)

KeyError: 'Yellow'

In [29]:
Test_0_2._desert_iterator("Player 3",verbose=1)

dict_keys(['D3', 'O3', 'D4', 'O4', 'D12', 'O12', 'D13', 'O13'])

In [30]:
## caution: starts game!
Test_0_2.game()


###################
#  Start Player?  #
###################

[41, 126]

                                           #####################                                       #########################
                                           ##  Current Field  ##                                       ##  Win Probabilities  ##
                                           #####################                                       #########################

     ════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      ║                      ║                      ║                      ║
     ║                      ║                      

SystemExit: 

c:\Users\eikeb\Anaconda3\Lib\site-packages\IPython\core\interactiveshell.py:3534: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)


In [29]:
rendered_field, inv_player_mask = render_field(demo2.game_field,demo2.players)
rendered_field

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 4,  5,  0,  0,  0,  0,  0],
       [ 7,  1,  2,  0,  0,  0,  0],
       [ 8, 10,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 6,  3,  0,  0,  0,  0,  0],
       [ 8, 11,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

In [8]:
print(Test_0_2.timers)

[{'one_turn_start': 0.0}, {'sim_all_moves_start': 19.020232439041138}, {'desert_iterator': 2.675877809524536}]


In [115]:
print({j:i[1] for j,i in Test_0_2.DO_fields_payoffs.items()}, Test_0_2.base_DO_hits)
print(Test_0_2.timers)

{'W7': array([[0.        ],
       [0.45450103],
       [0.        ],
       [0.        ]]), 'D3': array([[0.13888889],
       [0.45616998],
       [0.        ],
       [0.        ]]), 'O3': array([[0.16738683],
       [0.45447817],
       [0.        ],
       [0.        ]]), 'D4': array([[0.16904721],
       [0.46307442],
       [0.        ],
       [0.        ]]), 'O4': array([[0.19588477],
       [0.45339792],
       [0.        ],
       [0.        ]]), 'D7': array([[1.11653235],
       [0.38098708],
       [0.        ],
       [0.        ]]), 'O7': array([[1.05014861],
       [0.4395176 ],
       [0.        ],
       [0.        ]]), 'D8': array([[1.18545668],
       [0.4553898 ],
       [0.        ],
       [0.        ]]), 'O8': array([[1.1310671 ],
       [0.44168953],
       [0.        ],
       [0.        ]]), 'D12': array([[0.26373743],
       [0.45450103],
       [0.        ],
       [0.        ]]), 'O12': array([[0.25190192],
       [0.44967633],
       [0.        ],
       [

In [ ]:
player_index = list(Test_0_2.players.keys()).index("Player 1")
print(player_index)

for i in Test_0_2.DO_fields_payoffs.keys():
    field_payoff = Test_0_2.DO_fields_payoffs[i]
    ## delta base is the expected payoff of the players plate minus the base payoff of the plate of the player.
    delta = -Test_0_2.base_DO_hits[player_index,0] +field_payoff[1][player_index] ## create copy of delta base
    ## THIS player additionally gains, if the other players lose hits.
    delta_other_players_hits = np.delete(Test_0_2.base_DO_hits, player_index)-np.delete(field_payoff[1], player_index)

    delta+=np.sum(delta_other_players_hits)

    print(i,Test_0_2.base_DO_hits[player_index,0],-field_payoff[1][player_index],Test_0_2.base_DO_hits[player_index,0] -field_payoff[1][player_index])
    print(np.delete(Test_0_2.base_DO_hits, player_index),np.delete(field_payoff[1], player_index),delta_other_players_hits.sum())
    print(delta)

    #print(Test_0_2.base_payoffs,current_payoffs, delta_payoff_matrix,delta_inventory_payoffs)

    print()

0
W7 1.1165323502514861 [-0.] [1.11653235]
[0.38098708 0.         0.        ] [0.45450103 0.         0.        ] -0.07351394604481026
[-1.1900463]

D3 1.1165323502514861 [-0.13888889] [0.97764346]
[0.38098708 0.         0.        ] [0.45616998 0.         0.        ] -0.07518289894833102
[-1.05282636]

O3 1.1165323502514861 [-0.16738683] [0.94914552]
[0.38098708 0.         0.        ] [0.45447817 0.         0.        ] -0.07349108367626883
[-1.0226366]

D4 1.1165323502514861 [-0.16904721] [0.94748514]
[0.38098708 0.         0.        ] [0.46307442 0.         0.        ] -0.08208733424782805
[-1.02957247]

O4 1.1165323502514861 [-0.19588477] [0.92064758]
[0.38098708 0.         0.        ] [0.45339792 0.         0.        ] -0.07241083676268861
[-0.99305841]

D7 1.1165323502514861 [-1.11653235] [0.]
[0.38098708 0.         0.        ] [0.38098708 0.         0.        ] 0.0
[0.]

O7 1.1165323502514861 [-1.05014861] [0.06638374]
[0.38098708 0.         0.        ] [0.4395176 0.        0.     

#### solving problems with camel index finder

In [69]:
rendered_field, inv_player_mask = render_field(demo2.game_field,demo2.players)
camel_row_idx_base = np.zeros(8, dtype=np.int64)
camel_col_idx_base = np.zeros(8, dtype=np.int64)
camels_not_thrown = [1,2,3,4,5,6]
if 6 in camels_not_thrown:  # Extended version (7 camels)
    camel_ids = np.arange(1, 8)
else:
    camel_ids = np.arange(1, 6)
for i in camel_ids:
    pos = np.argwhere(rendered_field == i)
    camel_row_idx_base[i] = pos[0][0]
    camel_col_idx_base[i] = pos[0][1]


In [72]:
camel_ids

array([1, 2, 3, 4, 5, 6, 7])

In [71]:
camel_col_idx_base

array([0, 1, 2, 1, 0, 1, 0, 0], dtype=int64)

In [8]:
Camels = tuple(["Purple", "Blue", "Orange", "Yellow", "Green"])
index_of_camel = Camels.index("Orange")
index_of_camel

2